# Generated by Django 2.2.6 on 2019-10-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transação'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='transação',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterField(
            model_name='transação',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transação',
            name='observações',
            field=models.TextField(blank=True, null=True),
        ),
    ]
